version: '3.8'
services:
  nexus-rtc-postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: realtime_communication_db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_persistence_layer:/var/lib/postgresql/data
    restart: unless-stopped

  nexus-rtc-backend:
    build: ./backend
    container_name: nexus-rtc-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://nexus-rtc-postgres:5432/realtime_communication_db
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATA_REDIS_HOST: redis
      # Inject MinIO/S3 Environment Credentials to establish clean integration connections
      AWS_ACCESS_KEY_ID: devuser
      AWS_SECRET_ACCESS_KEY: devpassword
      MINIO_URL: http://minio.localhost:9000
      MINIO_BUCKET_NAME: nexus-rtc-attachments
    depends_on:
      - nexus-rtc-postgres
      - nexus-rtc-redis
      - nexus-rtc-minio
    restart: unless-stopped

  nexus-rtc-frontend:
    build: ./frontend
    container_name: nexus-rtc-frontend
    ports:
      - "80:80"
    depends_on:
      - nexus-rtc-backend
    restart: unless-stopped

  nexus-rtc-coturn:
    image: coturn/coturn:latest
    container_name: nexus-rtc-coturn
    ports:
       - "3478:3478"
       - "3478:3478/udp"
       - "5349:5349"
       - "5349:5349/udp" 
       # Range for the actual video data
       - "49152-49252:49152-49252/udp"   
    volumes:
      - ./coturn/turnserver.conf:/etc/turnserver.conf:ro
    command: turnserver -c /etc/turnserver.conf --log-file=stdout
    restart: unless-stopped
  
  nexus-rtc-redis:
    image: redis:7-alpine
    container_name: nexus-rtc-redis
    ports:
      - "6379:6379" # Maps the networking port to your host machine for test runners
    volumes:
      - redisdata:/data

  # MinIO S3-compatible cloud storage infrastructure
  nexus-rtc-minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: nexus-rtc-minio
    ports:
      - "9000:9000"        # S3 API Data Stream Interface
      - "9001:9001"        # Web Administrator Dashboard Console 
    environment:
      MINIO_ROOT_USER: devuser
      MINIO_ROOT_PASSWORD: devpassword
    volumes:
      - miniodata:/data
    # command instructs the image to start the server and bind the console web routing assets cleanly
    networks:
      default:
        # Bridges the internal Docker network layer cleanly
        aliases:
          - minio.localhost # a custom local domain setup in /etc/hosts (MAC) that points to 127.0.0.1 so front and backend can use the same endpoint url for S3 Signature V4 cryptographic hash matching
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  pg_persistence_layer:
    driver: local
  redisdata:
    driver: local
  miniodata:
    driver: local