apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtc-backend
  labels:
    app: rtc-portfolio
    component: backend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: rtc-portfolio
      component: backend
  template:
    metadata:
      labels:
        app: rtc-portfolio
        component: backend
    spec:
      # InitContainer prevents application pods from crashing if the database is still initializing
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for postgres-db-service to listen on port 5432...";
              until nc -z -w 2 postgres-db-service 5432; do sleep 2; done;
              echo "Database layer detected! Booting application microservice...";
      containers:
      - name: backend
        # Image tags are mapped to local registry names compiled during the Jenkins pipeline process
        image: rtc-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: api-port
        env:
          # Centralized Configuration Injection
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: rtc-app-config
                key: SPRING_DATASOURCE_URL
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: rtc-app-config
                key: POSTGRES_USER
          - name: SPRING_DATA_REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: rtc-app-config
                key: SPRING_DATA_REDIS_HOST
          - name: SPRING_DATA_REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: rtc-app-config
                key: SPRING_DATA_REDIS_PORT
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              configMapKeyRef:
                name: rtc-app-config
                key: AWS_ACCESS_KEY_ID
          - name: MINIO_URL
            valueFrom:
              configMapKeyRef:
                name: rtc-app-config
                key: MINIO_URL
          - name: MINIO_BUCKET_NAME
            valueFrom:
              configMapKeyRef:
                name: rtc-app-config
                key: MINIO_BUCKET_NAME
          
          # Secure Base64 Encrypted Secret Injection
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rtc-app-secrets
                key: postgres-password
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: rtc-app-secrets
                key: minio-root-password
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: rtc-app-secrets
                key: jwt-secret

        # Proactive health tracking keeps faulty nodes out of routing pools
        livenessProbe:
          tcpSocket:
            port: 8080  # Verifies the port socket is open & listening
          initialDelaySeconds: 95
          periodSeconds: 15
        readinessProbe:
          tcpSocket:
            port: 8080 # Verifies the port socket is open & listening
          initialDelaySeconds: 85
          periodSeconds: 15

        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"

      hostAliases:
        # - ip: "10.104.71.86"
        - ip: "10.101.60.142" # ingress-nginx-controller CLUSTER-IP retrieved by running `kubectl get svc -n ingress-nginx ingress-nginx-controller`
          hostnames:
            - "storage.nexus-rtc.localhost"
---
apiVersion: v1
kind: Service
metadata:
  name: rtc-backend-service
  labels:
    app: rtc-portfolio
    component: backend
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: rtc-portfolio
    component: backend
  # ClusterIP keeps services shielded inside the internal core network mesh
  type: ClusterIP
