-- =========================================================================
-- BASELINE DATABASE CHANGE CONTROL SCHEMAS
-- =========================================================================

-- 1. SYSTEM USER ENTITIES
CREATE TABLE IF NOT EXISTS users (
                                     id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                     email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_username UNIQUE (username)
    );

-- 2. ISOLATED CHANNEL ROOM ENTITIES
CREATE TABLE IF NOT EXISTS channels (
                                        id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                        created_at timestamp(6) without time zone NOT NULL,
    name character varying(50) NOT NULL,
    CONSTRAINT channels_pkey PRIMARY KEY (id),
    CONSTRAINT uk_channels_name UNIQUE (name)
    );

-- 3. INTERSECTING MEMBERSHIP MATRIX JOIN PLATE
CREATE TABLE IF NOT EXISTS channel_members (
                                               joined_at timestamp(6) without time zone NOT NULL,
    channel_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT channel_members_pkey PRIMARY KEY (channel_id, user_id),
    CONSTRAINT fk_members_channel FOREIGN KEY (channel_id) REFERENCES channels(id) ON DELETE CASCADE,
    CONSTRAINT fk_members_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    );

-- 4. MULTIMEDIA CONVERSATION HISTORY LOG ENTITIES
CREATE TABLE IF NOT EXISTS messages (
                                        id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                        content character varying(255),
    sender character varying(255),
    "timestamp" timestamp(6) without time zone,
    channel_id bigint NOT NULL,
    type character varying(255) NOT NULL,
    attachment_path character varying(255),
    attachment_type character varying(255),
    CONSTRAINT messages_pkey PRIMARY KEY (id),
    CONSTRAINT messages_type_check CHECK (((type)::text = ANY ((ARRAY['CHAT'::character varying, 'JOIN'::character varying, 'LEAVE'::character varying])::text[])))
    );

-- 5. ACCESS INDEX PERFORMANCE OPTIMIZATIONS
CREATE INDEX IF NOT EXISTS idx_messages_channel_lookup ON messages(channel_id);
