spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/realtime_communication_db
    username: dev
    password: password
  jpa:
    hibernate:
      ddl-auto: validate # Guard data profiles by relying strictly on Flyway SQL files!
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379

  # FLYWAY AUTOMATED INGRESS SETUP:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true # Prevents crashes if a persistent local volume already has columns initialized

aws:
  access:
    key:
      id: ${AWS_ACCESS_KEY_ID:devuser}
  secret:
    access:
      key: ${AWS_SECRET_ACCESS_KEY:devpassword}
minio:
  url: ${MINIO_URL:http://minio.localhost:9000}
  bucket:
    name: ${MINIO_BUCKET_NAME:nexus-rtc-attachments}

# JWT Secret (TODO: Move to env variables in production!)
app:
  jwtSecret: yourSecureRandomSecretKeyThatIsAtLeast32CharactersLong!!
  jwtExpirationMs: 86400000

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    com.portfolio.realtimecommunication: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.org.hibernate.jpa: DEBUG
    org.springframework.jdbc.datasource: DEBUG
    org.springframework.web.cors: TRACE
    org.springframework.security: DEBUG